[package]
name = "comunica-link-queue-parser-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
regex = "1.10.5"
serde = {version="1.0.204", features= ["derive"]}
serde_json = { version = "1.0.120", default-features = true, features = ["alloc"] }
